// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO4Le9rRwC1tdGawunrZXRaxRg4_PeS7M',
    appId: '1:180651392538:web:d6c455b26ab329569e9ba3',
    messagingSenderId: '180651392538',
    projectId: 'sweetstock-app-fase3',
    authDomain: 'sweetstock-app-fase3.firebaseapp.com',
    storageBucket: 'sweetstock-app-fase3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkddckPt4HqNE8_cq08wB_7sTD5iBtQVc',
    appId: '1:180651392538:android:c625477a83b6f8609e9ba3',
    messagingSenderId: '180651392538',
    projectId: 'sweetstock-app-fase3',
    storageBucket: 'sweetstock-app-fase3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Jqtmrx1MY5OIfndFotPqa3XFDABCuk8',
    appId: '1:180651392538:ios:eb2cfa7550c4c4759e9ba3',
    messagingSenderId: '180651392538',
    projectId: 'sweetstock-app-fase3',
    storageBucket: 'sweetstock-app-fase3.firebasestorage.app',
    iosBundleId: 'com.example.sweetstockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Jqtmrx1MY5OIfndFotPqa3XFDABCuk8',
    appId: '1:180651392538:ios:eb2cfa7550c4c4759e9ba3',
    messagingSenderId: '180651392538',
    projectId: 'sweetstock-app-fase3',
    storageBucket: 'sweetstock-app-fase3.firebasestorage.app',
    iosBundleId: 'com.example.sweetstockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO4Le9rRwC1tdGawunrZXRaxRg4_PeS7M',
    appId: '1:180651392538:web:3455855208ccd14f9e9ba3',
    messagingSenderId: '180651392538',
    projectId: 'sweetstock-app-fase3',
    authDomain: 'sweetstock-app-fase3.firebaseapp.com',
    storageBucket: 'sweetstock-app-fase3.firebasestorage.app',
  );
}
